"use strict";
const byId=id=>document.getElementById(id); let indexData=null,openedDay=null,openedGeneration=null,userMoved=false;
const controls=["severity","job-filter","operation-filter","text-filter"];
const formatTime=value=>new Date(value).toLocaleString();
function matches(record){const severity=byId("severity").value;const job=byId("job-filter").value.toLowerCase();const operation=byId("operation-filter").value.toLowerCase();const query=byId("text-filter").value.toLowerCase();const haystack=[record.component,record.event,record.reason,record.stage,record.operation_kind].filter(Boolean).join(" ").toLowerCase();return(!severity||record.severity===severity)&&(!job||(record.job_display_name??"").toLowerCase().includes(job))&&(!operation||(record.operation_id??"").toLowerCase().includes(operation))&&(!query||haystack.includes(query));}
function render(){const root=byId("log-records");root.replaceChildren();if(!openedDay)return;openedDay.records.filter(matches).forEach(record=>{const row=document.createElement("article");row.className=`log-row ${record.severity}`;row.dataset.eventId=record.event_id;row.append(Object.assign(document.createElement("time"),{textContent:formatTime(record.timestamp)}),Object.assign(document.createElement("span"),{textContent:record.severity}),Object.assign(document.createElement("span"),{textContent:record.component}),Object.assign(document.createElement("span"),{className:"message",textContent:[record.event,record.job_display_name,record.operation_kind,record.stage,record.reason].filter(Boolean).join(" · ")}));root.append(row);});byId("log-status").textContent=`${root.children.length} of ${openedDay.records.length} records · generation ${openedGeneration}`;}
async function fetchIndex(){try{const next=await fetch("/backup-status/logs/index.json",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error(`index HTTP ${r.status}`);return r.json();});const select=byId("log-date"),selected=select.value;indexData=next;select.replaceChildren(...next.days.map(day=>Object.assign(document.createElement("option"),{value:day.date,textContent:`${day.date} (${day.record_count})`})));if(next.days.length===0){byId("log-status").textContent="No log records yet";return;}if(selected&&next.days.some(day=>day.date===selected))select.value=selected;const current=next.days.find(day=>day.date===select.value);if(openedGeneration&&current&&current.generation_id!==openedGeneration)byId("log-change").classList.remove("hidden");if(!openedDay&&current)await loadSelected(true);}catch(error){byId("log-status").textContent=String(error);}}
async function loadSelected(initial=false){const entry=indexData?.days.find(day=>day.date===byId("log-date").value);if(!entry)return;const anchor=document.elementFromPoint(20,byId("log-records").getBoundingClientRect().top+10)?.closest("[data-event-id]")?.dataset.eventId;try{const next=await fetch(`/backup-status/logs/${encodeURIComponent(entry.file)}`,{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error(`log HTTP ${r.status}`);return r.json();});openedDay=next;openedGeneration=next.generation_id;byId("log-change").classList.add("hidden");render();if(anchor){document.querySelector(`[data-event-id="${CSS.escape(anchor)}"]`)?.scrollIntoView();}else if(initial&&!userMoved){byId("log-records").scrollTop=byId("log-records").scrollHeight;}}catch(error){byId("log-status").textContent=`Keeping previous data: ${String(error)}`;}}
controls.forEach(id=>byId(id).addEventListener("input",()=>{userMoved=true;render();}));byId("log-date").addEventListener("change",()=>{openedDay=null;openedGeneration=null;userMoved=false;loadSelected(true);});byId("refresh-log").addEventListener("click",()=>loadSelected(false));byId("log-records").addEventListener("scroll",()=>{userMoved=true;},{passive:true});fetchIndex();window.setInterval(fetchIndex,15000);
