"use strict";
const byId = id => document.getElementById(id);
const text = (tag, value, className) => { const node=document.createElement(tag); node.textContent=value ?? "not reported"; if(className) node.className=className; return node; };
const formatTime = value => value ? new Date(value).toLocaleString() : "not reported";
const formatDuration = seconds => seconds == null ? "not reported" : `${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m`;
const formatBytes = value => { if(value==null) return "not reported"; const units=["B","KiB","MiB","GiB","TiB"]; let size=value,index=0; while(size>=1024&&index<units.length-1){size/=1024;index++;} return `${size.toFixed(index?1:0)} ${units[index]}`; };
const addFact = (list,label,value) => { list.append(text("dt",label),text("dd",value)); };

function renderHealth(data, health) {
  const card=byId("health"); card.className=`health-card ${data.overall_health}`;
  byId("health-title").textContent=data.overall_health;
  byId("health-meta").textContent=`Manager ${health.manager_state} · backup disk ${data.backup_disk_state} · ${health.version} · started ${formatTime(health.manager_started_at)}`;
  const list=byId("health-issues"); list.replaceChildren();
  data.health_issues.forEach(issue=>list.append(text("li",`${issue.subject}: ${issue.summary}`,issue.severity)));
}
function renderOperations(items) {
  const root=byId("operations"); root.replaceChildren();
  if(!items.length){root.append(text("p","Nothing is running right now","notice"));return;}
  items.forEach(item=>{const row=text("article",null,"operation");row.append(text("div",item.state==="running"?"RUN":`#${item.position}`,"position"));const body=document.createElement("div");body.append(text("strong",`${item.job_display_name} · ${item.kind}`),text("p",`${item.stage??item.state} · ${formatDuration(item.elapsed_seconds)}`,"muted"));if(item.progress?.bytes_total){const bar=document.createElement("progress");bar.max=item.progress.bytes_total;bar.value=item.progress.bytes_done??0;body.append(bar);}row.append(body,text("code",item.operation_id));root.append(row);});
}
function runLabel(run){return run?`${run.state}${run.result?` / ${run.result}`:""}${run.stage?` / ${run.stage}`:""} · ${formatDuration(run.duration_seconds)}`:"not recorded";}
function renderJobs(items){const root=byId("jobs");root.replaceChildren();items.forEach(job=>{const card=text("article",null,"card");const head=document.createElement("header");const title=document.createElement("div");title.append(text("h3",job.display_name),text("p",`${job.kind} · ${job.job_id}`,"muted"));head.append(title,text("span",job.health,"badge "+job.health));const facts=text("dl",null,"facts");addFact(facts,"Reason",job.health_reason);addFact(facts,"Last run",runLabel(job.last_run));addFact(facts,"Previous",runLabel(job.previous_run));addFact(facts,"Last success",formatTime(job.last_success_at));addFact(facts,"Next",`${job.next_operation??"unknown"} · ${formatTime(job.next_fire_at)}`);addFact(facts,"Deadline",job.deadline??"not configured");addFact(facts,"Protected",formatBytes(job.backup_metrics?.protected_logical_bytes));addFact(facts,"Added",formatBytes(job.backup_metrics?.repository_added_bytes));card.append(head,facts);root.append(card);});}
function renderDisks(items){const root=byId("disks");root.replaceChildren();items.forEach(disk=>{const card=text("article",null,"card");const head=document.createElement("header");head.append(text("h3",disk.model??disk.disk_id),text("span",disk.smart_health,"badge "+disk.smart_health));const facts=text("dl",null,"facts");addFact(facts,"Public ID",disk.disk_id);addFact(facts,"Type / bus",`${disk.media_type} / ${disk.bus_type??"unknown"}`);addFact(facts,"State",disk.operational_state);addFact(facts,"Capacity",formatBytes(disk.capacity_bytes));addFact(facts,"Observed",formatTime(disk.observed_at));Object.entries(disk.metrics).forEach(([name,metric])=>addFact(facts,name,`${metric.current??"not reported"} · Δ ${metric.delta??"n/a"} · 24h ${metric.change_24h??"n/a"} · 30d ${metric.change_30d??"n/a"}`));card.append(head,facts);root.append(card);});}
function renderVolumes(items){const root=byId("volumes");root.replaceChildren();items.forEach(volume=>{const card=text("article",null,"card");card.append(text("h3",volume.display_name));const facts=text("dl",null,"facts");addFact(facts,"State",volume.stale?"stale / unknown":volume.online?"online":"offline");addFact(facts,"Disk",volume.disk_id);addFact(facts,"Filesystem",volume.filesystem);addFact(facts,"Used",formatBytes(volume.used_bytes));addFact(facts,"Free",`${formatBytes(volume.free_bytes)}${volume.free_percent==null?"":` (${volume.free_percent.toFixed(1)}%)`}`);addFact(facts,"Observed",formatTime(volume.observed_at));card.append(facts);root.append(card);});}
async function loadStatus(){try{const health=await fetch("/backup-status/health.json",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error(`health HTTP ${r.status}`);return r.json();});const data=await fetch("/backup-status/status.json",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error(`status HTTP ${r.status}`);return r.json();});if(data.generation_id!==health.generation_id)throw new Error("projection generation is changing; retrying");renderHealth(data,health);renderOperations(data.operations);renderJobs(data.jobs);renderDisks(data.disks);renderVolumes(data.volumes);byId("updated").textContent=`updated ${formatTime(data.generated_at)}`;byId("connection").className="notice hidden";}catch(error){byId("connection").textContent=String(error);byId("connection").className="notice error";}}
loadStatus(); window.setInterval(loadStatus,10000);
